os: linux

script: sleep 20m

dist: focal

jobs:
  include:
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: amd64
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
